### ISSUE TITLE
Broken Links 

### ISSUE THREAD

**Issue by gooseleggs** [openziti/ziti-doc#393]
On this page:  https://docs.openziti.io/docs/learn/core-concepts/security/authentication/totp/#enforcement

the _Authentication Policies_ and _Posture Checks_  are broken links.

**Comment by gooseleggs** [comment]
Also broken here: https://docs.openziti.io/docs/learn/core-concepts/security/authorization/posture-checks/ under the heading MFA

**Comment by dovholuknf** [comment]
i wonder why our broken link checker isn't finding those... thanks for reporting. will be fixed with https://github.com/openziti/ziti-doc/pull/394

**Comment by dovholuknf** [comment]
Thanks. should be fixed/published in a minute or two

**Comment by qrkourier** [comment]
Analysis: the issue is reproducible in Chrome incognito, but very puzzling indeed. [YouTube video summarizing the my finding](https://youtu.be/AIIXq1P_XcE).

Vercel preview from before you fixed busted links:
    https://ziti-law4nk1eh-openziti.vercel.app/docs/learn/core-concepts/security/authentication/totp/

The Markdown link Goosleggs encountered on page `/docs/learn/core-concepts/security/authentication/totp/` was `./authentication-policies` which resolved to `/docs/learn/core-concepts/security/authentication/totp/authentication-policies`, which you corrected to `/docs/learn/core-concepts/security/authentication/authentication-policies` by qualifying the relative link with the source filename.

The old, broken reference was actually creating a valid HTML rendering at build time, which is why Docusaurus build succeeded and all user agents (Chrome, Muffet, HTTPie, and cURL) get HTTP OK when they request the correct link directly which is the link that appears in the HTML rendered by Docusaurus.

However, for some reason, Chrome sees the correct URL in the HTML rendering at first, and then replaces that with the incorrect URL when it's clicked in the browser: 
    https://ziti-law4nk1eh-openziti.vercel.app/docs/learn/core-concepts/security/authentication/totp/authentication-policies

If I use Chrome's back button to return to `/docs/learn/core-concepts/security/authentication/totp/` now the HTML source in Chrome is updated with the incorrect link. A refresh of the page restores the correct URL in the HTML, and the error is repeatable: clicking the link somehow gets the incorrect URL and it's temporarily updated in the page's HTML.
